### ISSUE TITLE
App crash at Main Scenario

### ISSUE THREAD

**Issue by Spazzze** [UnknownX7/ReAction#20]
hi! First of all thanks for your plugin and for the work, it's very useful.

I want to report an app crash it reproduces 100% at Main Scenario Castrum Meridianum nearly in the middle of dung completion. (I've crashed 3 times in a row)

```
Stack trace:
   at System.Environment.get_StackTrace()
   at Dalamud.EntryPoint.VehCallback(IntPtr dumpPath, IntPtr logPath, IntPtr log) in C:\goatsoft\companysecrets\dalamud\EntryPoint.cs:line 68
   at ReAction.ActionStackManager.TryTabTarget(UInt32 actionID, Int64 objectID, Int64& newObjectID) in D:\a\ReAction\ReAction\ActionStackManager.cs:line 260
   at ReAction.ActionStackManager.OnUseAction(ActionManager* actionManager, UInt32 actionType, UInt32 actionID, Int64 targetObjectID, UInt32 param, UInt32 useType, Int32 pvp, Boolean* isGroundTarget) in D:\a\ReAction\ReAction\ActionStackManager.cs:line 96
   at DelvUI.Helpers.InputsHelper.HandleRequestAction(Int64 arg1, UInt32 arg2, UInt32 arg3, Int64 arg4, Int32 arg5, Int32 arg6, Int32 arg7, Byte* arg8) in D:\Projects\delvui\DelvUI\Helpers\InputsHelper.cs:line 193
   at Dalamud.Game.Framework.HandleFrameworkUpdate(IntPtr framework) in C:\goatsoft\companysecrets\dalamud\Game\Framework.cs:line 269
```

[dalamud_appcrash.log](https://github.com/UnknownX7/ReAction/files/7790577/dalamud_appcrash.log)

This is my settings for ReAction:

![image](https://user-images.githubusercontent.com/8989548/147702957-427427f5-0e3d-4882-95d0-04f62358581a.png)

The stacks are empty for now.

It seems to me that it crashes when the cutscene begins but we still have alive enemies. It tries to target an enemy and crashes, but I can be wrong

**Comment by IGP** [comment]
Can confirm that I had crashes in CM/Prae when using the plugin as well.

**Comment by UnknownX7** [comment]
Is there any specific cutscene it crashes on? The option causing the crash is indeed "Enable Auto Target", but I wasn't able to reproduce it myself. I went ahead and added some checks, so let me know if it's still occurring.

**Comment by bm01** [comment]
It may or may not be related, but I experienced a similar crash upon using a key item during a quest that asked me to decorate stairs with flowers (Delightful Decorations).
This was after a restart. Before restarting, it would say "invalid target".
Disabling "Enable Auto Change Target" solved it.
v1.1.3.1

**Comment by Dogger4Lifer** [comment]
can confirm I did experience the crash in castrum after killing the 2nd boss, was spamming a skill and right when he died i crashed.
Latest ReAction update I just experienced a crash while in a hunt train, as soon as the hunt mob died I crashed while I was spamming my button. Haven't been to castrum yet.

**Comment by UnknownX7** [comment]
This crash should no longer be possible after the latest update, so if you are still experiencing any and can verify that it is one of the options under "Other Settings", please open a new issue.

**Comment by Spazzze** [comment]
Also can confirm: I've checked today - problem is gone thanks!
